# Generated by Django 5.1.6 on 2025-03-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sav_Vintage_app', '0002_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveBigIntegerField(),
        ),
    ]
